# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [20]:
A = np.arange(1, 16).reshape(3,5)

In [21]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)


2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [22]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [23]:
BC1 = B - C
BC2 = B * C
BC3 = B @ C

print(B)
print(C)
print(BC1)
print(BC2)
print(BC3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [24]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(np.exp(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [30]:
print(np.min(B))

1


In [36]:
print(np.min(B,axis=1))

[1 4 7]


In [37]:
print(np.min(B, axis=0))

[1 2 3]


In [34]:
print(np.argmin(B))

0


In [38]:
print(np.argmin(B, axis=1))

[0 0 0]


In [41]:
print(np.sum(B))

np.int64(45)

In [43]:
print(np.mean(B, axis=0))

[4. 5. 6.]


In [44]:
print(np.median(B, axis=0))

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [45]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [46]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [51]:
# It means that you are asking for specific row. 
# In the case of A[1] you are asking for row 2 since indexing startts at 0

np.int64(7)

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [52]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [55]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [56]:
for i in np.nditer(A):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [57]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# Since we are imputing 3 dimentions '2, 3 ,-1' it means that we want out array to have 3 dimentions. 
# (if you imput -1 as a dimension you ask numpy to calculate the size of the last dimention)
# In this case we are telling numpy tp create an Array with 2 rows where each row contains an 3 by '-1' array.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [59]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [60]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [61]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [160]:
"""def add_mult_matrices(a: np.ndarray, b: np.ndarray, c):
    if (c == '+' or c == 'add') and a.shape == b.shape:
        print(a + b)
    elif (c == '+' or c == 'add') and a.shape != b.shape:
        print('Matrices not same size')
    elif (c == '*' or c == 'multiply') and a.shape[1] != b.shape[0]:
        print('Invalid format on matrices')
    elif (c == '*' or c == 'multiply') and a.shape[1] == b.shape[0]:
        print(a @ b)
    else:
        (print('Invalid input')) """

In [4]:
def add_mult_matrices(a, b, c):
    if isinstance(a, np.ndarray) and isinstance(b, np.ndarray):
        if (c == '+' or c == 'add') and a.shape == b.shape:
            print(a + b)
        elif (c == '+' or c == 'add') and a.shape != b.shape:
            print('Matrices not same size')
        elif (c == '*' or c == 'multiply') and a.shape[1] != b.shape[0]:
            print('Invalid format on matrices')
        elif (c == '*' or c == 'multiply') and a.shape[1] == b.shape[0]:
            print(a @ b)
        else:
            (print('Invalid input')) 
    else:
        (print('Invalid input'))

In [164]:
U = np.array([[1,1],[2,2]])
Y = np.array([[3],[3]])

In [167]:
add_mult_matrices(U, Y, 'add')
add_mult_matrices(U, Y, '*')
add_mult_matrices(U, Y, '-')

Matrices not same size
[[ 6]
 [12]]
Invalid input


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [168]:
x = np.array([4,3])
print(x)
print(x.ndim)
print(x*5)
print(x*3)
print(x*5 + x*3)
print(x*8)
print(x*4-x)
print(x.T)
y = np.atleast_2d(x.T)
print(y)

add_mult_matrices(x, y, 'add'),
np.linalg.norm(x)

[4 3]
1
[20 15]
[12  9]
[32 24]
[32 24]
[12  9]
[4 3]
[[4 3]]
Matrices not same size


np.float64(5.0)

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [158]:
A = np.array([[2, 1,-1], [1, -1, 1]])
B = np.array([[4, -2, 1],[2, -4, 2]])
C = np.array([[1,2],[2,1]])
D = np.array([[3,4],[4,3]])
E = np.array([[1],[2]])
I = np.array([[1,0],[0,1]])

In [175]:
print(A*2)
add_mult_matrices(B, -(A*2),'+')
add_mult_matrices((C*3),-(E*2), '+')
add_mult_matrices((D*2), -(C*3), '+')
add_mult_matrices((D.T), (D*2), '+')
add_mult_matrices(2*C.T, -(3*D.T), '+')
add_mult_matrices(A.T, -B, '+')
add_mult_matrices(A, C, '*')
add_mult_matrices(C, D, '*')
add_mult_matrices(C, D, '*')
add_mult_matrices(C, I, '*')
add_mult_matrices(A, B.T, '*')



[[ 4  2 -2]
 [ 2 -2  2]]
[[ 0 -4  3]
 [ 0 -2  0]]
Matrices not same size
[[3 2]
 [2 3]]
[[ 9 12]
 [12  9]]
[[-7 -8]
 [-8 -7]]
Matrices not same size
Invalid format on matrices
[[11 10]
 [10 11]]
[[11 10]
 [10 11]]
[[1 2]
 [2 1]]
[[ 5 -2]
 [ 7  8]]


In [12]:
A = np.array([[2, 3, 4], [5, 4, 1]])

add_mult_matrices(A, (A).T, '*')

[[29 26]
 [26 42]]


In [17]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

add_mult_matrices(A, B, '*') == add_mult_matrices(A, C, '*')

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]


True

In [19]:
B != C

array([[ True,  True],
       [ True,  True]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [179]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]
[  0   1   2 123]
[  2 123]


In [184]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [185]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
# Not sure if the answers were supposed to be in the doc already. But views hold the same memory as another object. 
# As such any changes made to the view object (as discovred with .base) also changes the original. 
# A copy has new memory assingend to it and will thus not affect the original when chnaged.